server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: book-management-backend

  datasource:
    url: jdbc:mysql://localhost:3306/book_management
    username: root
    password: phanloc2702

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: classpath:/static/, file:uploads/

jwt:
  signerKey: "tZwa1Se0sysrRZ9Bv0NOs4CWEUK2JTA8rDk9etuliNEl920NUbOzeUcsPHM88btR"

upload:
  dir: uploads  # thư mục lưu ảnh, tạo trong thư mục gốc của project

logging:
  level:
    com.bookmanagement: DEBUG
    org.hibernate.SQL: DEBUG
